spring:
  datasource:
    url: jdbc:mysql://localhost:3306/findmymeme_db
    username: meme
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
