spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/findmymeme_db
    username: meme
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    defer-datasource-initialization: true
  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
file:
  upload:
    temp-dir: /temps
    image-dir: /images
  base-dir: C:/Users/ACY/filestore
server:
  base-url: http://localhost:8080