spring:
  datasource:
    url: jdbc:mysql://localhost:3306/findmymeme_db
    username: meme
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000