name: Deploy to EC2

on:
  workflow_run:
    workflows: [ "Build and Push Docker Image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and pull images
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            
            cd /home/ubuntu/
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/find-my-meme-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/find-my-meme-backend:latest
            
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            docker-compose down
            
            DB_HOST=${{ secrets.DB_HOST }} \
            DB_PORT=${{ secrets.DB_PORT }} \
            DB_NAME=${{ secrets.DB_NAME }} \
            DB_USERNAME=${{ secrets.DB_USERNAME }} \
            DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            AWS_REGION=${{ secrets.AWS_REGION }} \
            AWS_BUCKET=${{ secrets.AWS_BUCKET }} \
            FILE_BASEURL=${{ secrets.FILE_BASEURL }} \
            FILE_BASEDIR=${{ secrets.FILE_BASEDIR }} \
            DEFAULT_PROFILE_URL=${{ secrets.DEFAULT_PROFILE_URL }} \
            REACT_APP_FILE_BASEURL=${{ secrets.REACT_APP_FILE_BASEURL }} \
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
          
            docker-compose up -d