name: Deploy to EC2

on:
  workflow_run:
    workflows: [ "Build and Push Docker Image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and pull images
        uses: appleboy/ssh-action@latest
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Pull the latest images on EC2
            docker pull ${{ secrets.DOCKER_USERNAME }}/find-my-meme-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/find-my-meme-backend:latest
            
            # Navigate to the directory containing docker-compose.yml
            cd /home/ubuntu/
            
            # Stop and remove existing containers
            docker-compose down
            
            # Start new containers with the updated images
            DB_HOST=${{ secrets.DB_HOST }} \
            DB_PORT=${{ secrets.DB_PORT }} \
            DB_NAME=${{ secrets.DB_NAME }} \
            DB_USERNAME=${{ secrets.DB_USERNAME }} \
            DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            AWS_REGION=${{ secrets.AWS_REGION }} \
            AWS_BUCKET=${{ secrets.AWS_BUCKET }} \
            FILE_BASEURL=${{ secrets.FILE_BASEURL }} \
            FILE_BASEDIR=${{ secrets.FILE_BASEDIR }} \
            DEFAULT_PROFILE_URL=${{ secrets.DEFAULT_PROFILE_URL }} \
            docker-compose up -d